Repository rohan9024/ecommerce, pull requests merged in 2022-12, with the labels that each got.

#25 Created a responsive navbar with hamburger menu
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Fifth.js
  src/components/First.js
  src/components/Footer.js
  src/components/Fourth.js
  src/components/Header.js
  src/components/Home.js
  src/components/Kids.js
  src/components/Men.js
  src/components/Mid.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/Second.js
  src/components/Third.js
  src/components/Women.js
Labels: points:20, codepeak 22

#43 Env
  ENVinstructions.md
  src/firebase.js
Labels: codepeak 22, points:5

#41 Made the shoes page responsive
  src/components/Shoes.js
Labels: codepeak 22

#103 Added single product description for each item in mens page
  src/App.js
  src/components/Men.js
  src/components/ShoeItem.js
  src/pages/ProductDescription.js
Labels: codepeak 22, points:10

#102 Made shoes page responsive
  src/components/Men.js
  src/components/Shoes.js
Labels: codepeak 22

#100 Made women's page responsive
  src/components/Men.js
  src/components/Women.js
Labels: codepeak 22, points:5
