Repository rohan9024/ecommerce, pull requests merged in 2023-12, with the labels that each got.

#143 Add form validation and error handle on Signup page
  src/Signup.js
Labels: codepeak 23, Medium

#150 validate login and signup form #138
  package-lock.json
  package.json
  src/Login.js
  src/Signup.js
Labels: codepeak 23, Medium

#170 Elements from navbar hover bar all redirectable
  public/index.html
  src/JsonData/data.js
  src/assets/electronics/sales10.jpg
  src/assets/img24.png
  src/assets/kids/img19.jpg
  src/assets/kids/img20.jpg
  src/assets/women/img68.png
  src/assets/women/img69.png
  src/assets/women/img8.png
  src/components/Kids.js
  src/components/Men.js
  src/components/Navbar.js
  src/components/SaleItem.js
  src/components/Sales.js
  src/components/ShoeItem.js
  src/components/Shoes.js
  src/components/Women.js
  src/pages/ProductDescription.js
Labels: codepeak 23

#173 added a 404 page #171
  src/404-page.js
  src/App.js
Labels: codepeak 23, Easy
